export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  images?: string[];
  rating: number;
  reviewCount: number;
  category: string;
  brand: string;
  description: string;
  specifications?: Record<string, string>;
  variants?: {
    type: string;
    options: string[];
  }[];
  stock: number;
  seller: {
    id: string;
    name: string;
  };
  isDeal?: boolean;
  isTrending?: boolean;
  isNewArrival?: boolean;
  isHidden?: boolean; // For hiding/unpublishing products
  isFestive?: boolean; // For festive season sale products
  isElectronics?: boolean; // For electronics mega sale
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  image?: string;
}

export interface CartItem {
  productId: string;
  product: Product;
  quantity: number;
  variant?: Record<string, string>;
}

export interface Order {
  id: string;
  date: string;
  total: number;
  status: 'pending' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled';
  items: CartItem[];
  shippingAddress: Address;
}

export interface Address {
  id: string;
  name: string;
  phone: string;
  street: string;
  city: string;
  postalCode: string;
  landmark?: string;
  isDefault: boolean;
}

export const categories: Category[] = [
  { id: '1', name: 'Fashion', icon: 'Shirt' },
  { id: '2', name: 'Electronics', icon: 'Laptop' },
  { id: '3', name: 'Beauty', icon: 'Sparkles' },
  { id: '4', name: 'Grocery', icon: 'ShoppingBasket' },
  { id: '5', name: 'Accessories', icon: 'Watch' },
  { id: '6', name: 'Home', icon: 'Home' },
  { id: '7', name: 'Toys', icon: 'Gamepad2' },
  { id: '8', name: 'Sports', icon: 'Dumbbell' },
  { id: '9', name: 'Books', icon: 'BookOpen' },
];

export const products: Product[] = [
  // Fashion Products
  {
    id: 'f1',
    name: 'Premium Cotton T-Shirt',
    price: 799,
    originalPrice: 1299,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
    ],
    rating: 4.2,
    reviewCount: 156,
    category: 'Fashion',
    brand: 'StyleHub',
    description: 'Comfortable 100% cotton t-shirt perfect for everyday wear.',
    variants: [
      { type: 'Size', options: ['S', 'M', 'L', 'XL'] },
      { type: 'Color', options: ['White', 'Black', 'Navy', 'Gray'] },
    ],
    stock: 120,
    seller: { id: 's2', name: 'Fashion Junction' },
    isDeal: true,
    isTrending: true,
  },
  {
    id: 'f2',
    name: 'Slim Fit Denim Jeans',
    price: 2499,
    originalPrice: 3999,
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
    rating: 4.5,
    reviewCount: 234,
    category: 'Fashion',
    brand: 'DenimCo',
    description: 'Classic slim fit jeans with stretch comfort.',
    variants: [
      { type: 'Size', options: ['28', '30', '32', '34', '36'] },
      { type: 'Color', options: ['Blue', 'Black', 'Gray'] },
    ],
    stock: 85,
    seller: { id: 's2', name: 'Fashion Junction' },
    isDeal: true,
  },
  {
    id: 'f3',
    name: 'Formal Shirt White',
    price: 1599,
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500',
    rating: 4.3,
    reviewCount: 98,
    category: 'Fashion',
    brand: 'FormalWear',
    description: 'Crisp white formal shirt for office and events.',
    variants: [
      { type: 'Size', options: ['S', 'M', 'L', 'XL', 'XXL'] },
    ],
    stock: 67,
    seller: { id: 's2', name: 'Fashion Junction' },
    isNewArrival: true,
  },
  {
    id: 'f4',
    name: 'Summer Floral Dress',
    price: 2199,
    originalPrice: 3499,
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500',
    rating: 4.6,
    reviewCount: 187,
    category: 'Fashion',
    brand: 'StyleHub',
    description: 'Beautiful floral print dress perfect for summer.',
    variants: [
      { type: 'Size', options: ['S', 'M', 'L', 'XL'] },
      { type: 'Color', options: ['Red', 'Blue', 'Yellow'] },
    ],
    stock: 43,
    seller: { id: 's2', name: 'Fashion Junction' },
    isTrending: true,
    isNewArrival: true,
  },
  {
    id: 'f5',
    name: 'Leather Jacket',
    price: 5999,
    originalPrice: 8999,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
    rating: 4.7,
    reviewCount: 156,
    category: 'Fashion',
    brand: 'LeatherLux',
    description: 'Premium leather jacket with modern styling.',
    variants: [
      { type: 'Size', options: ['M', 'L', 'XL'] },
      { type: 'Color', options: ['Black', 'Brown'] },
    ],
    stock: 28,
    seller: { id: 's6', name: 'Premium Fashion' },
    isDeal: true,
    isTrending: true,
  },
  {
    id: 'f6',
    name: 'Casual Hoodie',
    price: 1899,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
    rating: 4.4,
    reviewCount: 276,
    category: 'Fashion',
    brand: 'StreetStyle',
    description: 'Comfortable hoodie for casual wear.',
    variants: [
      { type: 'Size', options: ['S', 'M', 'L', 'XL'] },
      { type: 'Color', options: ['Gray', 'Black', 'Navy'] },
    ],
    stock: 145,
    seller: { id: 's2', name: 'Fashion Junction' },
    isNewArrival: true,
  },
  {
    id: 'f7',
    name: 'Sports Track Pants',
    price: 1299,
    image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=500',
    rating: 4.3,
    reviewCount: 134,
    category: 'Fashion',
    brand: 'SportMax',
    description: 'Comfortable track pants for workout and casual wear.',
    variants: [
      { type: 'Size', options: ['M', 'L', 'XL', 'XXL'] },
      { type: 'Color', options: ['Black', 'Navy', 'Gray'] },
    ],
    stock: 98,
    seller: { id: 's3', name: 'Sports Galaxy' },
  },
  {
    id: 'f8',
    name: 'Winter Coat',
    price: 4599,
    originalPrice: 6999,
    image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=500',
    rating: 4.8,
    reviewCount: 89,
    category: 'Fashion',
    brand: 'WinterWear',
    description: 'Warm and stylish winter coat.',
    variants: [
      { type: 'Size', options: ['M', 'L', 'XL'] },
      { type: 'Color', options: ['Black', 'Khaki'] },
    ],
    stock: 34,
    seller: { id: 's6', name: 'Premium Fashion' },
    isDeal: true,
  },

  // Electronics Products
  {
    id: 'e1',
    name: 'Premium Wireless Headphones',
    price: 4999,
    originalPrice: 6999,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800',
    ],
    rating: 4.5,
    reviewCount: 328,
    category: 'Electronics',
    brand: 'AudioMax',
    description: 'Experience premium sound quality with active noise cancellation.',
    specifications: {
      'Battery Life': '30 hours',
      'Connectivity': 'Bluetooth 5.0',
      'Driver Size': '40mm',
    },
    variants: [
      { type: 'Color', options: ['Black', 'Silver', 'Blue'] },
    ],
    stock: 45,
    seller: { id: 's1', name: 'Tech Store BD' },
    isDeal: true,
    isTrending: true,
  },
  {
    id: 'e2',
    name: 'Gaming Mouse RGB',
    price: 1499,
    originalPrice: 1999,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500',
    rating: 4.5,
    reviewCount: 298,
    category: 'Electronics',
    brand: 'GamePro',
    description: 'High-precision gaming mouse with customizable RGB lighting.',
    variants: [
      { type: 'Color', options: ['Black', 'White'] },
    ],
    stock: 78,
    seller: { id: 's1', name: 'Tech Store BD' },
    isDeal: true,
  },
  {
    id: 'e3',
    name: 'Mechanical Keyboard',
    price: 3999,
    originalPrice: 5499,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500',
    rating: 4.7,
    reviewCount: 412,
    category: 'Electronics',
    brand: 'GamePro',
    description: 'RGB mechanical gaming keyboard with blue switches.',
    variants: [
      { type: 'Layout', options: ['TKL', 'Full Size'] },
    ],
    stock: 56,
    seller: { id: 's1', name: 'Tech Store BD' },
    isTrending: true,
  },
  {
    id: 'e4',
    name: '4K Webcam',
    price: 2799,
    image: 'https://images.unsplash.com/photo-1593642532400-2682810df593?w=500',
    rating: 4.4,
    reviewCount: 167,
    category: 'Electronics',
    brand: 'TechView',
    description: '4K resolution webcam for streaming and video calls.',
    stock: 89,
    seller: { id: 's1', name: 'Tech Store BD' },
    isNewArrival: true,
  },
  {
    id: 'e5',
    name: 'Portable Bluetooth Speaker',
    price: 2199,
    originalPrice: 3499,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500',
    rating: 4.6,
    reviewCount: 523,
    category: 'Electronics',
    brand: 'AudioMax',
    description: 'Waterproof portable speaker with 20-hour battery life.',
    variants: [
      { type: 'Color', options: ['Black', 'Blue', 'Red'] },
    ],
    stock: 134,
    seller: { id: 's1', name: 'Tech Store BD' },
    isDeal: true,
    isTrending: true,
  },
  {
    id: 'e6',
    name: 'Wireless Mouse',
    price: 899,
    image: 'https://images.unsplash.com/photo-1586920740099-e6f0df06dab7?w=500',
    rating: 4.2,
    reviewCount: 245,
    category: 'Electronics',
    brand: 'TechGear',
    description: 'Ergonomic wireless mouse with silent clicks.',
    variants: [
      { type: 'Color', options: ['Black', 'White', 'Gray'] },
    ],
    stock: 167,
    seller: { id: 's1', name: 'Tech Store BD' },
  },
  {
    id: 'e7',
    name: 'USB-C Hub 7-in-1',
    price: 1799,
    image: 'https://images.unsplash.com/photo-1625948515291-69613efd103f?w=500',
    rating: 4.5,
    reviewCount: 189,
    category: 'Electronics',
    brand: 'TechGear',
    description: 'Multi-port USB-C hub with HDMI, USB 3.0, and card reader.',
    stock: 92,
    seller: { id: 's1', name: 'Tech Store BD' },
    isNewArrival: true,
  },
  {
    id: 'e8',
    name: 'Power Bank 20000mAh',
    price: 1599,
    originalPrice: 2299,
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=500',
    rating: 4.4,
    reviewCount: 678,
    category: 'Electronics',
    brand: 'PowerTech',
    description: 'High capacity power bank with fast charging.',
    stock: 203,
    seller: { id: 's1', name: 'Tech Store BD' },
    isDeal: true,
  },
  {
    id: 'e9',
    name: 'Smart LED Bulb',
    price: 699,
    image: 'https://images.unsplash.com/photo-1550985616-10810253b84d?w=500',
    rating: 4.3,
    reviewCount: 156,
    category: 'Electronics',
    brand: 'SmartHome',
    description: 'WiFi enabled color changing LED bulb.',
    stock: 234,
    seller: { id: 's7', name: 'Smart Home Store' },
    isNewArrival: true,
  },
  {
    id: 'e10',
    name: 'Laptop Stand Aluminum',
    price: 1299,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500',
    rating: 4.6,
    reviewCount: 123,
    category: 'Electronics',
    brand: 'TechGear',
    description: 'Ergonomic aluminum laptop stand with adjustable height.',
    stock: 78,
    seller: { id: 's1', name: 'Tech Store BD' },
  },

  // Beauty Products
  {
    id: 'b1',
    name: 'Makeup Kit Professional',
    price: 1999,
    originalPrice: 2999,
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=500',
    rating: 4.8,
    reviewCount: 412,
    category: 'Beauty',
    brand: 'GlamBeauty',
    description: 'Complete makeup kit with 24 essential products.',
    stock: 34,
    seller: { id: 's4', name: 'Beauty World' },
    isDeal: true,
    isTrending: true,
  },
  {
    id: 'b2',
    name: 'Skincare Set',
    price: 2499,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500',
    rating: 4.7,
    reviewCount: 289,
    category: 'Beauty',
    brand: 'SkinGlow',
    description: 'Complete skincare routine with cleanser, toner, and moisturizer.',
    stock: 67,
    seller: { id: 's4', name: 'Beauty World' },
    isNewArrival: true,
    isTrending: true,
  },
  {
    id: 'b3',
    name: 'Hair Dryer Professional',
    price: 3299,
    originalPrice: 4999,
    image: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=500',
    rating: 4.5,
    reviewCount: 234,
    category: 'Beauty',
    brand: 'HairTech',
    description: 'Professional hair dryer with ionic technology.',
    stock: 45,
    seller: { id: 's4', name: 'Beauty World' },
    isDeal: true,
  },
  {
    id: 'b4',
    name: 'Perfume Luxury Edition',
    price: 4999,
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=500',
    rating: 4.9,
    reviewCount: 567,
    category: 'Beauty',
    brand: 'FragrancePro',
    description: 'Long-lasting luxury perfume with floral notes.',
    variants: [
      { type: 'Scent', options: ['Floral', 'Woody', 'Fresh'] },
    ],
    stock: 89,
    seller: { id: 's4', name: 'Beauty World' },
    isTrending: true,
  },
  {
    id: 'b5',
    name: 'Face Mask Set 10pcs',
    price: 899,
    originalPrice: 1299,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=500',
    rating: 4.4,
    reviewCount: 345,
    category: 'Beauty',
    brand: 'SkinGlow',
    description: 'Variety pack of hydrating and brightening face masks.',
    stock: 156,
    seller: { id: 's4', name: 'Beauty World' },
    isDeal: true,
  },
  {
    id: 'b6',
    name: 'Lipstick Matte Collection',
    price: 599,
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500',
    rating: 4.6,
    reviewCount: 423,
    category: 'Beauty',
    brand: 'GlamBeauty',
    description: 'Long-lasting matte lipstick in 12 shades.',
    variants: [
      { type: 'Shade', options: ['Red', 'Pink', 'Nude', 'Coral'] },
    ],
    stock: 234,
    seller: { id: 's4', name: 'Beauty World' },
    isNewArrival: true,
  },
  {
    id: 'b7',
    name: 'Nail Polish Set',
    price: 799,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=500',
    rating: 4.3,
    reviewCount: 187,
    category: 'Beauty',
    brand: 'NailArt',
    description: '12-piece nail polish collection with various colors.',
    stock: 123,
    seller: { id: 's4', name: 'Beauty World' },
  },
  {
    id: 'b8',
    name: 'Eye Shadow Palette',
    price: 1299,
    originalPrice: 1899,
    image: 'https://images.unsplash.com/photo-1583241800698-c5e7d7a2c837?w=500',
    rating: 4.7,
    reviewCount: 298,
    category: 'Beauty',
    brand: 'GlamBeauty',
    description: '24-shade eyeshadow palette with shimmer and matte finishes.',
    stock: 78,
    seller: { id: 's4', name: 'Beauty World' },
    isDeal: true,
  },

  // Accessories Products
  {
    id: 'a1',
    name: 'Smart Watch Pro',
    price: 8999,
    originalPrice: 12999,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
    rating: 4.7,
    reviewCount: 542,
    category: 'Accessories',
    brand: 'SmartTech',
    description: 'Track fitness, monitor health, and stay connected.',
    specifications: {
      'Display': '1.4" AMOLED',
      'Battery': '7 days',
      'Water Resistance': '5ATM',
    },
    variants: [
      { type: 'Color', options: ['Black', 'Rose Gold', 'Silver'] },
    ],
    stock: 28,
    seller: { id: 's1', name: 'Tech Store BD' },
    isDeal: true,
    isTrending: true,
  },
  {
    id: 'a2',
    name: 'Luxury Handbag',
    price: 3499,
    originalPrice: 4999,
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500',
    rating: 4.4,
    reviewCount: 89,
    category: 'Accessories',
    brand: 'LuxeBrand',
    description: 'Elegant handbag made with premium vegan leather.',
    variants: [
      { type: 'Color', options: ['Black', 'Brown', 'Burgundy'] },
    ],
    stock: 15,
    seller: { id: 's2', name: 'Fashion Junction' },
    isDeal: true,
  },
  {
    id: 'a3',
    name: 'Leather Wallet',
    price: 1299,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=500',
    rating: 4.5,
    reviewCount: 234,
    category: 'Accessories',
    brand: 'LeatherLux',
    description: 'Genuine leather wallet with RFID protection.',
    variants: [
      { type: 'Color', options: ['Black', 'Brown', 'Tan'] },
    ],
    stock: 156,
    seller: { id: 's6', name: 'Premium Fashion' },
    isNewArrival: true,
  },
  {
    id: 'a4',
    name: 'Sunglasses UV Protection',
    price: 1899,
    originalPrice: 2999,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500',
    rating: 4.6,
    reviewCount: 178,
    category: 'Accessories',
    brand: 'VisionWear',
    description: 'Stylish sunglasses with 100% UV protection.',
    variants: [
      { type: 'Color', options: ['Black', 'Brown', 'Blue'] },
    ],
    stock: 98,
    seller: { id: 's2', name: 'Fashion Junction' },
    isDeal: true,
  },
  {
    id: 'a5',
    name: 'Backpack Laptop',
    price: 2499,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500',
    rating: 4.7,
    reviewCount: 456,
    category: 'Accessories',
    brand: 'TravelGear',
    description: 'Durable laptop backpack with USB charging port.',
    variants: [
      { type: 'Color', options: ['Black', 'Gray', 'Navy'] },
    ],
    stock: 123,
    seller: { id: 's8', name: 'Bag Store' },
    isTrending: true,
  },
  {
    id: 'a6',
    name: 'Belt Leather Classic',
    price: 899,
    image: 'https://images.unsplash.com/photo-1624222247344-550fb60583f0?w=500',
    rating: 4.3,
    reviewCount: 167,
    category: 'Accessories',
    brand: 'LeatherLux',
    description: 'Classic leather belt for formal and casual wear.',
    variants: [
      { type: 'Size', options: ['32', '34', '36', '38'] },
      { type: 'Color', options: ['Black', 'Brown'] },
    ],
    stock: 234,
    seller: { id: 's6', name: 'Premium Fashion' },
  },
  {
    id: 'a7',
    name: 'Phone Case Premium',
    price: 499,
    image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=500',
    rating: 4.4,
    reviewCount: 567,
    category: 'Accessories',
    brand: 'TechGear',
    description: 'Shockproof phone case with raised edges.',
    variants: [
      { type: 'Model', options: ['iPhone 14', 'iPhone 15', 'Samsung S23'] },
      { type: 'Color', options: ['Clear', 'Black', 'Blue'] },
    ],
    stock: 345,
    seller: { id: 's1', name: 'Tech Store BD' },
    isNewArrival: true,
  },
  {
    id: 'a8',
    name: 'Wrist Watch Analog',
    price: 2799,
    originalPrice: 3999,
    image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=500',
    rating: 4.5,
    reviewCount: 234,
    category: 'Accessories',
    brand: 'TimeKeeper',
    description: 'Elegant analog watch with leather strap.',
    variants: [
      { type: 'Color', options: ['Black', 'Brown', 'Blue'] },
    ],
    stock: 67,
    seller: { id: 's9', name: 'Watch House' },
    isDeal: true,
  },

  // Sports Products
  {
    id: 's1',
    name: 'Running Shoes',
    price: 2999,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
    rating: 4.6,
    reviewCount: 234,
    category: 'Sports',
    brand: 'SportMax',
    description: 'Lightweight running shoes with superior cushioning.',
    variants: [
      { type: 'Size', options: ['7', '8', '9', '10', '11'] },
      { type: 'Color', options: ['Black', 'White', 'Red'] },
    ],
    stock: 67,
    seller: { id: 's3', name: 'Sports Galaxy' },
    isTrending: true,
  },
  {
    id: 's2',
    name: 'Yoga Mat Premium',
    price: 1299,
    originalPrice: 1899,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500',
    rating: 4.7,
    reviewCount: 456,
    category: 'Sports',
    brand: 'YogaPro',
    description: 'Non-slip yoga mat with extra cushioning.',
    variants: [
      { type: 'Color', options: ['Purple', 'Blue', 'Pink', 'Black'] },
    ],
    stock: 189,
    seller: { id: 's3', name: 'Sports Galaxy' },
    isDeal: true,
  },
  {
    id: 's3',
    name: 'Dumbbell Set 20kg',
    price: 3499,
    image: 'https://images.unsplash.com/photo-1611672585731-fa10603fb9e0?w=500',
    rating: 4.5,
    reviewCount: 178,
    category: 'Sports',
    brand: 'FitGear',
    description: 'Adjustable dumbbell set for home workouts.',
    stock: 45,
    seller: { id: 's3', name: 'Sports Galaxy' },
    isNewArrival: true,
  },
  {
    id: 's4',
    name: 'Football Professional',
    price: 1599,
    image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=500',
    rating: 4.4,
    reviewCount: 289,
    category: 'Sports',
    brand: 'SportMax',
    description: 'Professional quality football for matches.',
    variants: [
      { type: 'Size', options: ['Size 4', 'Size 5'] },
    ],
    stock: 234,
    seller: { id: 's3', name: 'Sports Galaxy' },
  },
  {
    id: 's5',
    name: 'Badminton Racket',
    price: 2199,
    originalPrice: 2999,
    image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=500',
    rating: 4.6,
    reviewCount: 167,
    category: 'Sports',
    brand: 'RacketPro',
    description: 'Lightweight badminton racket with carbon fiber.',
    stock: 89,
    seller: { id: 's3', name: 'Sports Galaxy' },
    isDeal: true,
  },
  {
    id: 's6',
    name: 'Cycling Gloves',
    price: 699,
    image: 'https://images.unsplash.com/photo-1638097622250-e146d84f528a?w=500',
    rating: 4.3,
    reviewCount: 123,
    category: 'Sports',
    brand: 'CyclePro',
    description: 'Breathable cycling gloves with gel padding.',
    variants: [
      { type: 'Size', options: ['S', 'M', 'L', 'XL'] },
    ],
    stock: 167,
    seller: { id: 's3', name: 'Sports Galaxy' },
    isNewArrival: true,
  },
  {
    id: 's7',
    name: 'Swimming Goggles',
    price: 599,
    image: 'https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=500',
    rating: 4.5,
    reviewCount: 234,
    category: 'Sports',
    brand: 'AquaGear',
    description: 'Anti-fog swimming goggles with UV protection.',
    variants: [
      { type: 'Color', options: ['Blue', 'Black', 'Clear'] },
    ],
    stock: 156,
    seller: { id: 's3', name: 'Sports Galaxy' },
  },
  {
    id: 's8',
    name: 'Resistance Bands Set',
    price: 899,
    originalPrice: 1299,
    image: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500',
    rating: 4.4,
    reviewCount: 345,
    category: 'Sports',
    brand: 'FitGear',
    description: 'Set of 5 resistance bands for strength training.',
    stock: 198,
    seller: { id: 's3', name: 'Sports Galaxy' },
    isDeal: true,
  },

  // Home Products
  {
    id: 'h1',
    name: 'Coffee Maker Deluxe',
    price: 5499,
    image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=500',
    rating: 4.3,
    reviewCount: 167,
    category: 'Home',
    brand: 'HomeChef',
    description: 'Programmable coffee maker with thermal carafe.',
    specifications: {
      'Capacity': '12 cups',
      'Power': '900W',
    },
    stock: 22,
    seller: { id: 's5', name: 'Kitchen Essentials' },
    isNewArrival: true,
  },
  {
    id: 'h2',
    name: 'Blender High Speed',
    price: 3299,
    originalPrice: 4999,
    image: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=500',
    rating: 4.6,
    reviewCount: 289,
    category: 'Home',
    brand: 'HomeChef',
    description: 'Powerful blender for smoothies and soups.',
    stock: 67,
    seller: { id: 's5', name: 'Kitchen Essentials' },
    isDeal: true,
  },
  {
    id: 'h3',
    name: 'Bedsheet Cotton Set',
    price: 2499,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=500',
    rating: 4.7,
    reviewCount: 456,
    category: 'Home',
    brand: 'ComfortHome',
    description: 'Premium cotton bedsheet set with pillow covers.',
    variants: [
      { type: 'Size', options: ['Queen', 'King'] },
      { type: 'Color', options: ['White', 'Blue', 'Gray'] },
    ],
    stock: 123,
    seller: { id: 's10', name: 'Home Comfort' },
    isTrending: true,
  },
  {
    id: 'h4',
    name: 'Curtains Blackout',
    price: 1899,
    originalPrice: 2999,
    image: 'https://images.unsplash.com/photo-1585128719564-91615af2c787?w=500',
    rating: 4.5,
    reviewCount: 234,
    category: 'Home',
    brand: 'HomeDecor',
    description: 'Thermal blackout curtains for bedroom.',
    variants: [
      { type: 'Color', options: ['Gray', 'Beige', 'Navy'] },
    ],
    stock: 89,
    seller: { id: 's10', name: 'Home Comfort' },
    isDeal: true,
  },
  {
    id: 'h5',
    name: 'Vacuum Cleaner',
    price: 6999,
    originalPrice: 9999,
    image: 'https://images.unsplash.com/photo-1558317374-067fb0f6ca90?w=500',
    rating: 4.8,
    reviewCount: 378,
    category: 'Home',
    brand: 'CleanPro',
    description: 'Cordless vacuum cleaner with powerful suction.',
    stock: 34,
    seller: { id: 's5', name: 'Kitchen Essentials' },
    isDeal: true,
    isTrending: true,
  },
  {
    id: 'h6',
    name: 'Wall Clock Modern',
    price: 1299,
    image: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=500',
    rating: 4.4,
    reviewCount: 156,
    category: 'Home',
    brand: 'HomeDecor',
    description: 'Silent wall clock with modern design.',
    variants: [
      { type: 'Color', options: ['Black', 'White', 'Wood'] },
    ],
    stock: 167,
    seller: { id: 's10', name: 'Home Comfort' },
    isNewArrival: true,
  },
  {
    id: 'h7',
    name: 'Table Lamp LED',
    price: 899,
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=500',
    rating: 4.5,
    reviewCount: 234,
    category: 'Home',
    brand: 'LightHouse',
    description: 'Adjustable LED table lamp with touch control.',
    stock: 198,
    seller: { id: 's7', name: 'Smart Home Store' },
  },
  {
    id: 'h8',
    name: 'Kitchen Knife Set',
    price: 2199,
    originalPrice: 3299,
    image: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=500',
    rating: 4.6,
    reviewCount: 289,
    category: 'Home',
    brand: 'HomeChef',
    description: 'Professional kitchen knife set with wooden block.',
    stock: 56,
    seller: { id: 's5', name: 'Kitchen Essentials' },
    isDeal: true,
  },
  {
    id: 'h9',
    name: 'Microwave Oven',
    price: 8999,
    image: 'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=500',
    rating: 4.7,
    reviewCount: 456,
    category: 'Home',
    brand: 'HomeChef',
    description: 'Digital microwave oven with auto cook menus.',
    specifications: {
      'Capacity': '20L',
      'Power': '700W',
    },
    stock: 23,
    seller: { id: 's5', name: 'Kitchen Essentials' },
    isTrending: true,
  },
  {
    id: 'h10',
    name: 'Air Purifier',
    price: 7499,
    originalPrice: 9999,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=500',
    rating: 4.8,
    reviewCount: 345,
    category: 'Home',
    brand: 'CleanPro',
    description: 'HEPA air purifier for clean indoor air.',
    stock: 45,
    seller: { id: 's7', name: 'Smart Home Store' },
    isDeal: true,
    isNewArrival: true,
  },

  // Grocery Products
  {
    id: 'g1',
    name: 'Organic Rice 5kg',
    price: 499,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500',
    rating: 4.6,
    reviewCount: 567,
    category: 'Grocery',
    brand: 'OrganicFarm',
    description: 'Premium quality organic basmati rice.',
    stock: 234,
    seller: { id: 's11', name: 'Fresh Mart' },
  },
  {
    id: 'g2',
    name: 'Olive Oil Extra Virgin',
    price: 1299,
    originalPrice: 1699,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500',
    rating: 4.7,
    reviewCount: 289,
    category: 'Grocery',
    brand: 'MedOlive',
    description: 'Cold-pressed extra virgin olive oil.',
    stock: 123,
    seller: { id: 's11', name: 'Fresh Mart' },
    isDeal: true,
  },
  {
    id: 'g3',
    name: 'Honey Pure 500g',
    price: 599,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784099?w=500',
    rating: 4.8,
    reviewCount: 456,
    category: 'Grocery',
    brand: 'NatureSweet',
    description: '100% pure natural honey.',
    stock: 189,
    seller: { id: 's11', name: 'Fresh Mart' },
    isTrending: true,
  },
  {
    id: 'g4',
    name: 'Green Tea Organic',
    price: 399,
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=500',
    rating: 4.5,
    reviewCount: 234,
    category: 'Grocery',
    brand: 'TeaLeaf',
    description: 'Organic green tea leaves with antioxidants.',
    stock: 267,
    seller: { id: 's11', name: 'Fresh Mart' },
    isNewArrival: true,
  },
  {
    id: 'g5',
    name: 'Almond Nuts 500g',
    price: 899,
    originalPrice: 1199,
    image: 'https://images.unsplash.com/photo-1508736793122-f516e3ba5569?w=500',
    rating: 4.6,
    reviewCount: 345,
    category: 'Grocery',
    brand: 'NutriNuts',
    description: 'Premium quality almonds rich in protein.',
    stock: 156,
    seller: { id: 's11', name: 'Fresh Mart' },
    isDeal: true,
  },
  {
    id: 'g6',
    name: 'Dark Chocolate 70%',
    price: 349,
    image: 'https://images.unsplash.com/photo-1511381939415-e44015466834?w=500',
    rating: 4.7,
    reviewCount: 289,
    category: 'Grocery',
    brand: 'CocoaDelight',
    description: 'Premium dark chocolate with 70% cocoa.',
    stock: 234,
    seller: { id: 's11', name: 'Fresh Mart' },
  },
  {
    id: 'g7',
    name: 'Pasta Whole Wheat',
    price: 299,
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500',
    rating: 4.4,
    reviewCount: 178,
    category: 'Grocery',
    brand: 'PastaHouse',
    description: 'Healthy whole wheat pasta.',
    stock: 345,
    seller: { id: 's11', name: 'Fresh Mart' },
  },
  {
    id: 'g8',
    name: 'Peanut Butter Crunchy',
    price: 499,
    originalPrice: 649,
    image: 'https://images.unsplash.com/photo-1522778526097-ce0a22ceb253?w=500',
    rating: 4.6,
    reviewCount: 423,
    category: 'Grocery',
    brand: 'NutriNuts',
    description: 'Crunchy peanut butter with no added sugar.',
    stock: 189,
    seller: { id: 's11', name: 'Fresh Mart' },
    isDeal: true,
  },

  // Toys Products
  {
    id: 't1',
    name: 'Building Blocks 500pcs',
    price: 1899,
    originalPrice: 2699,
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500',
    rating: 4.7,
    reviewCount: 456,
    category: 'Toys',
    brand: 'KidBlocks',
    description: 'Creative building blocks set for children.',
    stock: 89,
    seller: { id: 's12', name: 'Toy Kingdom' },
    isDeal: true,
    isTrending: true,
  },
  {
    id: 't2',
    name: 'Remote Control Car',
    price: 2499,
    image: 'https://images.unsplash.com/photo-1558418157-1e2e31d8010b?w=500',
    rating: 4.6,
    reviewCount: 289,
    category: 'Toys',
    brand: 'RCPro',
    description: 'High-speed remote control racing car.',
    stock: 67,
    seller: { id: 's12', name: 'Toy Kingdom' },
    isNewArrival: true,
  },
  {
    id: 't3',
    name: 'Puzzle 1000 Pieces',
    price: 799,
    image: 'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=500',
    rating: 4.5,
    reviewCount: 234,
    category: 'Toys',
    brand: 'PuzzleMaster',
    description: 'Challenging 1000-piece jigsaw puzzle.',
    stock: 123,
    seller: { id: 's12', name: 'Toy Kingdom' },
  },
  {
    id: 't4',
    name: 'Stuffed Bear Large',
    price: 1599,
    originalPrice: 2199,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
    rating: 4.8,
    reviewCount: 567,
    category: 'Toys',
    brand: 'SoftToys',
    description: 'Large soft teddy bear for kids.',
    variants: [
      { type: 'Color', options: ['Brown', 'White', 'Pink'] },
    ],
    stock: 156,
    seller: { id: 's12', name: 'Toy Kingdom' },
    isDeal: true,
  },
  {
    id: 't5',
    name: 'Art Set for Kids',
    price: 1299,
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=500',
    rating: 4.6,
    reviewCount: 345,
    category: 'Toys',
    brand: 'ArtKids',
    description: 'Complete art set with colors and brushes.',
    stock: 98,
    seller: { id: 's12', name: 'Toy Kingdom' },
    isNewArrival: true,
  },
  {
    id: 't6',
    name: 'Board Game Family',
    price: 1899,
    image: 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?w=500',
    rating: 4.7,
    reviewCount: 289,
    category: 'Toys',
    brand: 'GameNight',
    description: 'Fun board game for the whole family.',
    stock: 134,
    seller: { id: 's12', name: 'Toy Kingdom' },
    isTrending: true,
  },

  // Books Products
  {
    id: 'bk1',
    name: 'Business Strategy Guide',
    price: 899,
    originalPrice: 1299,
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500',
    rating: 4.6,
    reviewCount: 234,
    category: 'Books',
    brand: 'BusinessPress',
    description: 'Comprehensive guide to business strategy.',
    stock: 167,
    seller: { id: 's13', name: 'Book Haven' },
    isDeal: true,
  },
  {
    id: 'bk2',
    name: 'Fiction Novel Bestseller',
    price: 599,
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500',
    rating: 4.8,
    reviewCount: 567,
    category: 'Books',
    brand: 'NovelHouse',
    description: 'Award-winning fiction novel.',
    stock: 234,
    seller: { id: 's13', name: 'Book Haven' },
    isTrending: true,
  },
  {
    id: 'bk3',
    name: 'Cooking Recipe Book',
    price: 799,
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500',
    rating: 4.5,
    reviewCount: 345,
    category: 'Books',
    brand: 'ChefBooks',
    description: '500+ recipes for home cooking.',
    stock: 123,
    seller: { id: 's13', name: 'Book Haven' },
    isNewArrival: true,
  },
  {
    id: 'bk4',
    name: 'Self Help Motivation',
    price: 699,
    originalPrice: 999,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500',
    rating: 4.7,
    reviewCount: 456,
    category: 'Books',
    brand: 'MindPress',
    description: 'Inspirational self-help book.',
    stock: 189,
    seller: { id: 's13', name: 'Book Haven' },
    isDeal: true,
  },
  {
    id: 'bk5',
    name: 'Children Story Collection',
    price: 499,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500',
    rating: 4.8,
    reviewCount: 389,
    category: 'Books',
    brand: 'KidsRead',
    description: 'Collection of classic children stories.',
    stock: 267,
    seller: { id: 's13', name: 'Book Haven' },
    isNewArrival: true,
  },
];

export const heroSlides = [
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1581486125780-0cf706d8cd69?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwc2hvcHBpbmclMjBzYWxlfGVufDF8fHx8MTc2MjAyMDEyMHww&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Summer Fashion Sale',
    subtitle: 'Up to 50% off on trending styles',
    cta: 'Shop Now',
    link: '/category/1',
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1758186355698-bd0183fc75ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBlbGVjdHJvbmljcyUyMHRlY2hub2xvZ3l8ZW58MXx8fHwxNzYxOTc1NDI5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Latest Electronics',
    subtitle: 'Discover cutting-edge technology',
    cta: 'Explore Now',
    link: '/category/2',
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1567169102475-a4a93aa6d71a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWF1dHklMjBjb3NtZXRpY3MlMjBsdXh1cnl8ZW58MXx8fHwxNzYxOTQ5NjcyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Beauty Essentials',
    subtitle: 'Glow up with premium beauty products',
    cta: 'Shop Beauty',
    link: '/category/3',
  },
  {
    id: 4,
    image: 'https://images.unsplash.com/photo-1724861233646-0f469e9ee27f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob21lJTIwZGVjb3IlMjBpbnRlcmlvcnxlbnwxfHx8fDE3NjE5NDI2NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Transform Your Home',
    subtitle: 'Modern home decor & furniture',
    cta: 'Browse Collection',
    link: '/category/6',
  },
];

export const mockUser = {
  id: 'u1',
  name: 'John Doe',
  email: 'john.doe@example.com',
  phone: '+880 1712-345678',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
};

export const mockAddresses: Address[] = [
  {
    id: 'a1',
    name: 'John Doe',
    phone: '+880 1712-345678',
    street: 'House 45, Road 12, Block C',
    city: 'Dhaka',
    postalCode: '1212',
    landmark: 'Near City Bank',
    isDefault: true,
  },
  {
    id: 'a2',
    name: 'John Doe',
    phone: '+880 1712-345678',
    street: '123 Main Street',
    city: 'Chittagong',
    postalCode: '4100',
    isDefault: false,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-2025-001',
    date: '2025-10-28',
    total: 12498,
    status: 'delivered',
    items: [
      {
        productId: 'e1',
        product: products.find((p) => p.id === 'e1')!,
        quantity: 1,
        variant: { Color: 'Black' },
      },
      {
        productId: 'a1',
        product: products.find((p) => p.id === 'a1')!,
        quantity: 1,
        variant: { Color: 'Silver' },
      },
    ],
    shippingAddress: mockAddresses[0],
  },
  {
    id: 'ORD-2025-002',
    date: '2025-10-30',
    total: 799,
    status: 'shipped',
    items: [
      {
        productId: 'f1',
        product: products.find((p) => p.id === 'f1')!,
        quantity: 1,
        variant: { Size: 'M', Color: 'Black' },
      },
    ],
    shippingAddress: mockAddresses[0],
  },
  {
    id: 'ORD-2025-003',
    date: '2025-11-01',
    total: 5998,
    status: 'pending',
    items: [
      {
        productId: 's1',
        product: products.find((p) => p.id === 's1')!,
        quantity: 2,
        variant: { Size: '9', Color: 'Black' },
      },
    ],
    shippingAddress: mockAddresses[0],
  },
];
